name: Code Quality
on:
  # Trigger the workflow on pushes to only the 'release' branches
  push:
    branches: [ 'release/*' ]
  # Trigger the workflow on any pull request
  pull_request:
    types: [ opened, reopened ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.4.0

      # Run Qodana inspections
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v4.2.5

      # Uploading a SARIF-formatted Qodana report to GitHub
      - name: Uploading Qodana report to GitHub
        if: ${{ false }}
        uses: github/codeql-action/upload-sarif@v1.1.2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
