
name: Code Quality
on:
  # Trigger the workflow on pushes to only the 'hotfix' and 'release' branches
  push:
    branches:
      - hotfix/*
      - release/*
  # Trigger the workflow on any pull request
  pull_request:
    types: [ opened, reopened ]
  # Trigger the workflow on manual dispatch
  workflow_dispatch:

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3.0.2

      # Run Qodana inspections
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2022.2.1

      # Uploading a SARIF-formatted Qodana report to GitHub
      - name: Uploading Qodana report to GitHub
        if: ${{ false }}
        uses: github/codeql-action/upload-sarif@v2.1.28
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true